# Dataset and Library
The sample data are [snippets](https://escholarship.org/uc/uciem_cpcem) from  Clinical Practice and Cases in Emergency Medicine case reports and [transformer](https://en.wikipedia.org/wiki/Transformer_(machine_learning_model)) models from the Python library,[huggingface](https://huggingface.co/transformers)

In [ ]:
%%capture
!pip install transformers

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("bvanaken/CORe-clinical-diagnosis-prediction")
model = AutoModelForSequenceClassification.from_pretrained("bvanaken/CORe-clinical-diagnosis-prediction")

In [ ]:
input = " A 58-year-old male presents to the emergency department with headache, hand numbness, and phantosmia."

In [ ]:
tokenized_input = tokenizer(input, return_tensors="pt")
output = model(**tokenized_input)

In [ ]:
predictions = torch.sigmoid(output.logits)
predicted_labels = [model.config.id2label[_id] for _id in (predictions > 0.3).nonzero()[:, 1].tolist()]

In [ ]:
output

SequenceClassifierOutput([('logits',
                           tensor([[ -9.2949,  -9.9079, -10.6348,  ..., -11.0518,  -6.9629,  -9.2351]],
                                  grad_fn=<AddmmBackward0>))])

In [ ]:
predictions

tensor([[9.1887e-05, 4.9779e-05, 2.4062e-05,  ..., 1.5858e-05, 9.4548e-04,
         9.7545e-05]], grad_fn=<SigmoidBackward0>)

In [ ]:
predicted_labels

['272',
 '401',
 '4019',
 'complication',
 'essential',
 'hemorrhage',
 'hypertension',
 'mention',
 'status',
 'unspecified',
 'use',
 'without']

In [ ]:
input2 = "We present a case of a 19-year-old female presenting with intermittent chest pain, palpitations, and weakness present for two months. The patient had previously been evaluated at our emergency department one week earlier ."

In [ ]:
tokenized_input2 = tokenizer(input2, return_tensors="pt")
output2 = model(**tokenized_input2)

In [ ]:
predictions2 = torch.sigmoid(output2.logits)
predicted_labels2 = [model.config.id2label[_id] for _id in (predictions2 > 0.3).nonzero()[:, 1].tolist()]

In [ ]:
output2

SequenceClassifierOutput([('logits',
                           tensor([[ -9.5360, -10.4061, -11.0893,  ..., -10.9782,  -6.7574,  -9.8357]],
                                  grad_fn=<AddmmBackward0>))])

In [ ]:
predictions2

tensor([[7.2203e-05, 3.0246e-05, 1.5274e-05,  ..., 1.7069e-05, 1.1609e-03,
         5.3503e-05]], grad_fn=<SigmoidBackward0>)

In [ ]:
predicted_labels2

['285',
 '2859',
 '424',
 '428',
 '4280',
 '780',
 'anemia',
 'artery',
 'congestive',
 'disorders',
 'heart',
 'specified',
 'unspecified']

In [ ]:
input3 = "A 60-year-old female presented with sudden onset visual disturbance in her right eye"

In [ ]:
tokenized_input3 = tokenizer(input3, return_tensors="pt")
output3 = model(**tokenized_input3)

In [ ]:
predictions3 = torch.sigmoid(output3.logits)
predicted_labels3 = [model.config.id2label[_id] for _id in (predictions3 > 0.3).nonzero()[:, 1].tolist()]

In [ ]:
predicted_labels3

['affecting', 'cerebral', 'disorder', 'infarction', 'type', 'unspecified']

In [ ]:
input4 = """We report the case of a 33-year-old, previously healthy male who presented to the emergency department for evaluation of transient, right-sided facial droop with visual changes. 
His symptoms began 12 days after falling off a scooter. Imaging revealed an extracranial internal CAD."""

In [ ]:
tokenized_input4 = tokenizer(input4, return_tensors="pt")
output4 = model(**tokenized_input4)

In [ ]:
predictions4 = torch.sigmoid(output4.logits)
predicted_labels4 = [model.config.id2label[_id] for _id in (predictions4 > 0.3).nonzero()[:, 1].tolist()]

In [ ]:
predicted_labels4

['348', '780', 'cerebral', 'mention', 'specified', 'unspecified', 'without']